name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "./docs/package.json"

      - name: Install dependencies
        run: npm ci
        working-directory: ./docs

      - name: Build
        run: npm run build
        working-directory: ./docs
        env:
          PUBLIC_URL: /HappiScope

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs/dist" # Vite builds to the dist directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
